@startuml
start

split
:1、张三师父带教期间的提成计算
(按月定时计算，初步定在28号进
行计算)；首先查找张三旗下弟子实
际结业月份15号<当前时间，但是没
有带教提成金额的弟子群体;
while (是否存在此类弟子群?)
    :不存在;
end while
    :存在(弟子迭代逐个计算);
if(是否存在了延期结业月份数据)) then (yes)
    if(是否存在结业提成比例) then (yes)
        :带教提成=（汇总弟子原带教期间(理应结业月份-开始月份)月份的计件总金额之和）*结业提成比例 +
         （汇总弟子延期带教期间(实际结业月份-理应结业月份)月份的计件总金额之和）*结业固定比例4%（后面需要有配置文件进行维护）
         记录时间、金额等数据到对应的弟子信息表，回到第一步的带教提成金额使用;
    else (no)
    endif
else (no)
    if(是否存在结业提成比例)) then(yes)
        :带教提成=汇总弟子在带教期间(实际结业月份-开始月份)月份的计件总金额之和*结业提成比例
         记录时间、金额等数据到对应的弟子信息表，回到第一步的带教提成金额使用；;
    else (no)
    endif
endif
split again
:2、张三师父弟子的结业提成计算
（按年定时计算，初步定在12月的
28号进行计算（12月份工资的结算
周期是到12月15号））；
一代弟子+二代弟子;
:定义变量
人均计件薪资=结业周期后月份至年底计件总金额/结业周期后月份至年底计件月数,
城市月均工资（hr城市）=城市人员月份计件总金额/城市人员计件总月数；
城市月份计件金额=月份中hr城市对应的所有本城市人员，本城市的计件金额之和，需要排除掉入职时间在当月的结算周期内的数据；并统计中月份计件人数；（单独存储起来）
城市人员月份计件总金额=每个月的HR城市计件总金额之和;城市人员计件总月数 = HR城市月份计件人数之和;
split again
:3、首先查找张三旗下弟子实际结
业月份15号<当年12月28号时间，
还未存在当年结业提成数据：;
while (是否存在此类弟子群?)
    :不存在;
end while
    :存在(弟子迭代逐个计算);
    split
        :人均计件薪资<城市月均工资（hr城市）;
    split again
        :人均计件薪资>=城市月均工资（hr城市）;
        :结业提成=汇总弟子在当年月份的计件总金额之和*结业固定比例2% (后面需要有配置文件进行维护）, 当年月份(如果是当年结业的则是，12-实际结业月份，其他都是全年计算)
             		记录数据到对应的弟子信息子表（新增表记录弟子每年对师父的结业贡献），回到第一步的当年结业提成使用.;
    end split
end split
stop
@enduml